export * from './pimp-1.jpeg';
export * from './kit-1.jpeg';
export * from './oscar-3.jpeg';
export * from './oscar-2.jpeg';
export * from './kit-3.jpeg';
export * from './oscar-1.jpeg';
export * from './kit-2.jpeg';
export * from './pimp-3.jpeg';
export * from './pimp-2.jpeg';
